server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: ''
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  
  security: 
      oauth2: 
        client: 
          registration: 
            google: 
              client-Id: 772165217548-rtrlnp9cja35hnbclamkjprnvjbv0nco.apps.googleusercontent.com
              client-secret: jgQ_tyghVcQj4-Zj_pBmrMaW
              scope:  
              - email
              - profile
             
              